export const LOGIN = 'LOGIN';
export const GET_TOYS = 'GET_TOYS';
export const CHANGE_INCOMIN = 'CHANGE_INCOMIN';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_FORM_CATEGORY = 'UPDATE_FORM_CATEGORY';
export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';